# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbuAEE-Rbj9uunctg0crqAJ2zSBnknyJ
"""

print("hello,這是我的第一行程式!")

name="小明"
age=20
print(name)
print(age)

name="小明"
food="鹽酥雞"
print(f"我是{name}，我最喜歡吃{food}！")

food=input("你今天想吃什麼食物?")
print(f"真巧，我也想吃{food}")

drink=int(input("請問這杯飲料多少錢?"))
print(f"買三杯需要{drink*3}元")

temp=float(input("請問你目前的體溫?"))
if temp>=38:
  print("你發燒了，禁止進入!")
elif temp<34:
  print("你的體溫過低，請盡速就醫!")
else:
  print("體溫正常，可進入!")

for i in range(1,6):
  print(f"這是我印出的第{i}遍!")

password=""
while password!="1234":
  password=input("請輸入密碼:")
  if password == "1234":
    print("密碼正確。")
  else:
    print("輸入錯誤。")

while True:
  password=input("請輸入密碼:")
  if password=="1234":
    print("密碼正確!")
    break
  else:
    print("密碼錯誤!")

my_list=["蘋果","香蕉","橘子"]
my_list.append(input("請問還要買什麼?"))
for i in my_list:
  print(f"我超想買{i}!")

secret=55
history=[]
while True:
  guess=int(input("請猜一個數字:"))
  history.append(guess)
  if guess>55:
    print("太大了!")
  elif guess<55:
    print("太小了!")
  else :
    print("正確!")
    break
print(f"你總共猜了這些數字:{history}")
print(f"你總共猜了{len(history)}次!")

cart=[]
while True:
  print("==選項==")
  print("1.新增物品")
  print("2.查看購物車")
  print("3.結帳")
  choice = input("請輸入選項 (1, 2, 3)：")
  if choice=="1":
    add=input("想買什麼?")
    cart.append(add)
    print(f"已經將{add}加入購物車。")
  elif choice=="2":
    print(f"目前共有{len(cart)}項物品!")
    print(f"你總共買了:{cart}")
  elif choice=="3":
    print("歡迎下次光臨!")
    break
  else:
    print("沒有這個選項!")

餘額=1000
while True:
  print("==選項==")
  print("1.查詢餘額 2.存錢 3.提款 4.退出")
  choice=input("請輸入選項(1,2,3,4):")
  if choice=="1":
    print(f"目前餘額為{餘額}元!")
  elif choice=="2":
    add=int(input("請輸入存款金額:"))
    餘額=餘額+(add)
    print(f"已存入{add}元!")
    print(f"目前餘額為{餘額}元!")
  elif choice=="3":
    det=int(input("請輸入提款金額:"))
    if det>餘額:
      print("餘額不足!")
    else:
      餘額=餘額-(det)
      print(f"已提款{det}元!")
      print(f"目前餘額為{餘額}元!")
  elif choice=="4":
    print("請拿回信用卡。")
    break
  else:
    print("沒有這個選項!")

slime_hp=50
while slime_hp>0:
  print("1.普通攻擊" "2.大招")
  attack=input("使用技能(1、2)")
  if attack=="1":
    slime_hp=slime_hp-5
    print(f"史萊姆受到傷害!目前血量:{slime_hp}")
  elif attack=="2":
    slime_hp=slime_hp-10
    print(f"史萊姆受到傷害!目前血量:{slime_hp}")
  else:
    slime_hp=slime_hp-0
    print(f"技能無效!目前血量:{slime_hp}")
print("戰鬥結束!")

menu={"紅茶":30,"奶茶":45,"綠茶":25}
total=0
while True:
  print(menu)
  order=input("請問要喝什麼?(按下結帳以結束)")
  if order in menu:
    total=total+menu[order]
    print(f"總花費{total}元。")
  elif order=="結帳":
    break
  else:
    print("沒有賣這個喔!")
print(f"你總共要花{total}元。")